### PR TITLE
Fix #18

### LINKED ISSUE #18: reportException with params
Please consider addding a reportException method to Rollbar and Notifier that also accepts additional params. Specifically, a method with signature would be perfect:

    void reportException(Throwable throwable, String level, String description, Map<String, String> params);

Sometimes, it's handy to have extra metadata related to a caught exception. Right now, it's hard to both report an exception (and take advantage of Notifier's exception processing logic) while also adding additional metadata. Adding this to the description is not ideal.

### PR DESCRIPTION
**Pull request by mpj**

### CODE REVIEW

**Comment by dlsteuer** [comment]
Hey @mpj thanks for this, looks pretty good. There is a bunch of duplication between the buildItemPayload methods, can you refactor this out to a common method?

**Comment by mpj** [comment]
@dlsteuer something like that?

**Comment by dlsteuer** [comment]
It's a good start, I would go even a little bit further and move 

```
            JSONObject body = new JSONObject();

            JSONArray jsonArray = makeTrace(throwable, description);

            body.put("trace_chain", jsonArray);

            if (level == null) {
                level = defaultCaughtExceptionLevel;
            }
```
into a buildBasePayload method or something named similar.

**Comment by mpj** [comment]
@dlsteuer I'll do it if you want to, this is your codebase, but I would not do it if it was mine. I think it's more preferable to have a little bit of duplication than hard-to-decipher indirection. makeTrace does a single thing that can (at least sort of) be deciphered from the function name. The code above does not have a clear singular purpose and is therefore, in my opinion, not suitable for extraction. John Carmack describes it a lot better than I do here: http://number-none.com/blow/blog/programming/2014/09/26/carmack-on-inlined-code.html

Extracting the code that reassigns level seems particularly convoluted, as it assigns a variable in the method scope, so the method would have multiple output variables (level + body). I could create an inner class representing the return value, but it's not semantically clear to me what that would be (BasePayload?) and the generalized amount of code I would add would be more than the sum of the duplicated code.

**Comment by dlsteuer** [comment]
I agree with what Carmack says, and I think he'd do something here, because there is very obvious code duplication that can lead to subtle bugs.
```
In almost all cases, code duplication is a greater evil than whatever second order problems arise from functions being called in different circumstances, so I would rarely advocate duplicating code to avoid a function, but in a lot of cases you can still avoid the function by flagging an operation to be performed at the properly controlled time
```
It's very clear that there is duplication here between the 2 functions, what about this, basically gut the first method and have it call the second with an empty map, then you could probably inline the makeTrace method again.

**Comment by dlsteuer** [comment]
@mpj thoughts on my comment?

**Pull request merged**
