### PR TITLE
add allow to customize Rollbar thread name 

### PR DESCRIPTION
**Pull request by c3ph3us**
add allow to customize Rollbar thread name 
- to be more friendly 
- and better recognizable as default while debugging or tracking if rollbar self is causing any mess :) 

from 0.1.3bc-initial
(cherry picked from commit ccbe145)

ps. second try to add something to this dead zone :)

### CODE REVIEW

**Comment by brianr** [comment]
Thanks @c3ph3us ! We will review this soon.

**Comment by c3ph3us** [comment]
ups  i didn't  include  upper Rollbar changes 
i will make new pull :)

**Comment by c3ph3us** [comment]
0.1.3bc-initial3 
-added one more init and prevent use of constructor

**Comment by c3ph3us** [comment]
1. from ceph3us branch
  	pulled files:
  	    - Notifier,.java
  	     - Rollbar.java
  	     - RollbarThread.java

     changelog: **0.1.3bc4**
             - add predefined levels eg: Rollbar.Level.DEBUG
             - rewrite RollbarThread include:
             - concurrency logic first step to minimize deadlocking
             - more verbosity for debugging

 2. correction to master branch
       - set notifier version to 0.1.4 ( before 0.1.2)

3. other files untouched

**Pull request closed without merging**
